# Generated by Django 3.1 on 2020-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('android', 'android'), ('ios', 'ios')], default='android', max_length=20)),
                ('form_factor', models.CharField(choices=[('phone', 'phone'), ('tablet', 'tablet')], default='phone', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
